# Automatically generated
# 
CLIP_FORMAT_AVI = 0
# 
FEATURE_BRIGHTNESS = 0
# 
FEATURE_EXPOSURE = 1
# 
FEATURE_SHARPNESS = 2
# 
FEATURE_WHITE_BAL = 3
# 
FEATURE_HUE = 4
# 
FEATURE_SATURATION = 5
# 
FEATURE_GAMMA = 6
# 
FEATURE_SHUTTER = 7
# 
FEATURE_GAIN = 8
# 
FEATURE_IRIS = 9
# 
FEATURE_FOCUS = 10
# 
FEATURE_TEMPERATURE = 11
# 
FEATURE_TRIGGER = 12
# 
FEATURE_ZOOM = 13
# 
FEATURE_PAN = 14
# 
FEATURE_TILT = 15
# 
FEATURE_OPT_FILTER = 16
# 
FEATURE_GPIO = 17
# 
FEATURE_FRAME_RATE = 18
# 
FEATURE_ROI = 19
# 
FEATURE_FLIP = 20
# 
FEATURE_DECIMATION = 21
# 
FEATURE_PIXEL_FORMAT = 22
# 
FEATURE_EXTENDED_SHUTTER = 23
# 
FEATURE_AUTO_ROI = 24
# 
FEATURE_LOOKUP_TABLE = 25
# 
FEATURE_MEMORY_CHANNEL = 26
# 
FEATURE_WHITE_SHADING = 27
# 
FEATURE_ROTATE = 28
#  Added to slow down imager to accomodate slow frame rates
FEATURE_IMAGER_CLK_DIVISOR = 29
#  Allows Trigger to be used more deterministicaly where
FEATURE_TRIGGER_WITH_CONTROLLED_LIGHT = 30
#  The number of bits used to represnt 16-bit data (10 or 12)
FEATURE_MAX_PIXEL_SIZE = 31
# 
FEATURES_TOTAL = 32
#  Really, decimation is just one type of pixel
FEATURE_PIXEL_ADDRESSING = 21
# 
FEATURE_ALL = 0xFFFFFFFF
# 
FEATURE_FLAG_PRESENCE = 0x00000001
# 
FEATURE_FLAG_MANUAL = 0x00000002
# 
FEATURE_FLAG_AUTO = 0x00000004
# 
FEATURE_FLAG_ONEPUSH = 0x00000008
# 
FEATURE_FLAG_OFF = 0x00000010
# 
FEATURE_FLAG_DESC_SUPPORTED = 0x00000020
# 
FEATURE_FLAG_READ_ONLY = 0x00000040
# 
IMAGE_FORMAT_BMP = 0x0000
# 
IMAGE_FORMAT_TIFF = 0x0001
# 
IMAGE_FORMAT_PSD = 0x0002
# 
IMAGE_FORMAT_JPEG = 0x0003
# 
IMAGE_FORMAT_RAW_RGB24 = 0x1005
# 
PIXEL_FORMAT_MONO8 = 0
# 
PIXEL_FORMAT_MONO16 = 1
# 
PIXEL_FORMAT_YUV422 = 2
# 
PIXEL_FORMAT_BAYER8_GRBG = 3
# 
PIXEL_FORMAT_BAYER16_GRBG = 4
# 
PIXEL_FORMAT_RGB24 = 5
# 
PIXEL_FORMAT_RGB48 = 6
# 
PIXEL_FORMAT_BAYER8_RGGB = 7
# 
PIXEL_FORMAT_BAYER8_GBRG = 8
# 
PIXEL_FORMAT_BAYER8_BGGR = 9
# 
PIXEL_FORMAT_BAYER16_RGGB = 10
# 
PIXEL_FORMAT_BAYER16_GBRG = 11
# 
PIXEL_FORMAT_BAYER16_BGGR = 12
# 
PIXEL_FORMAT_BAYER8 = 3
# 
PIXEL_FORMAT_BAYER16 = 4
# 
START_PREVIEW = 0
# 
PAUSE_PREVIEW = 1
# 
STOP_PREVIEW = 2
# 
START_STREAM = 0
# 
PAUSE_STREAM = 1
# 
STOP_STREAM = 2
# 
TRIGGER_TYPE_FREE_RUNNING = 0
# 
TRIGGER_TYPE_SOFTWARE = 1
# 
TRIGGER_TYPE_HARDWARE = 2
# 
PXL_MAX_STROBES = 16
# 
PXL_MAX_KNEE_POINTS = 4
# 
PXL_UPDATE_CAMERA = 0
# 
PXL_UPDATE_HOST = 1
# 
FACTORY_DEFAULTS_MEMORY_CHANNEL = 0
# 
OVERLAY_PREVIEW = 0x01
# 
OVERLAY_FORMAT_IMAGE = 0x02
# 
OVERLAY_FORMAT_CLIP = 0x04
# 
OVERLAY_FRAME = 0x08
